# Dependencies
markdown:         kramdown
highlighter:      rouge

plugins:
  - jekyll-paginate
  - jekyll-gist

# Permalinks
permalink:        pretty

# Setup
title:            Madison Anderson
tagline:          'Project Blog'
description:      'A place for thoughts and projects'
baseurl:          '/'

author:
  name:           'Madison Anderson'
  url:

paginate:         3

# Custom vars
version:          0.1

github:
  repo:           https://github.com/mvdi/hyde

collections:
  blog:
    permalink: /blog/:year/:month/:day/:title/
    output: true
  datascience:
    permalink: /datascience/:year/:month/:day/:title/
    output: true
